services:
    maildev:
        image: ${IMAGE:-maildev/maildev:2.0.5}
        container_name: ${CONTAINER_NAME:-maildev}
        ports:
            - ${WEB_PORT:-1080}:1080
            - ${SMTP_PORT:-1025}:1025
        restart: always
        networks:
            - maildev

networks:
    maildev:
        name: maildev
